const products = [
  {
    id: 1,
    name: "Wireless Bluetooth Headphones",
    price: 79.99,
    originalPrice: 129.99,
    category: "electronics",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop",
    rating: 4.5,
    reviews: 234,
    badge: "Sale",
    description: "Premium wireless headphones with active noise cancellation, 30-hour battery life, and crystal-clear sound quality. Perfect for music lovers and professionals.",
    features: ["Active Noise Cancellation", "30-Hour Battery", "Bluetooth 5.0", "Foldable Design"]
  },
  {
    id: 2,
    name: "Classic Leather Watch",
    price: 149.99,
    originalPrice: null,
    category: "fashion",
    image: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&h=400&fit=crop",
    rating: 4.8,
    reviews: 189,
    badge: null,
    description: "Elegant leather watch with Swiss movement, sapphire crystal glass, and genuine Italian leather strap. A timeless accessory for any occasion.",
    features: ["Swiss Movement", "Sapphire Crystal", "Italian Leather", "Water Resistant"]
  },
  {
    id: 3,
    name: "Running Sneakers Pro",
    price: 89.99,
    originalPrice: 119.99,
    category: "fashion",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop",
    rating: 4.3,
    reviews: 412,
    badge: "Sale",
    description: "Lightweight running shoes with responsive cushioning, breathable mesh upper, and durable rubber outsole for maximum performance.",
    features: ["Responsive Cushioning", "Breathable Mesh", "Durable Rubber Outsole", "Lightweight"]
  },
  {
    id: 4,
    name: "Smart Home Speaker",
    price: 59.99,
    originalPrice: null,
    category: "electronics",
    image: "https://images.unsplash.com/photo-1543512214-318c7553f230?w=400&h=400&fit=crop",
    rating: 4.6,
    reviews: 567,
    badge: "Popular",
    description: "Voice-controlled smart speaker with premium sound, built-in virtual assistant, and smart home integration for a connected lifestyle.",
    features: ["Voice Control", "Premium Sound", "Smart Home Hub", "Multi-Room Audio"]
  },
  {
    id: 5,
    name: "Organic Coffee Beans",
    price: 24.99,
    originalPrice: 34.99,
    category: "food",
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400&h=400&fit=crop",
    rating: 4.7,
    reviews: 892,
    badge: "Sale",
    description: "Premium single-origin organic coffee beans, medium roast with notes of chocolate and caramel. Ethically sourced from sustainable farms.",
    features: ["Single Origin", "Organic Certified", "Medium Roast", "Fair Trade"]
  },
  {
    id: 6,
    name: "Yoga Mat Premium",
    price: 45.99,
    originalPrice: null,
    category: "sports",
    image: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400&h=400&fit=crop",
    rating: 4.4,
    reviews: 321,
    badge: null,
    description: "Extra thick, non-slip yoga mat made from eco-friendly materials. Perfect for yoga, pilates, and home workouts.",
    features: ["Extra Thick 6mm", "Non-Slip Surface", "Eco-Friendly", "Carry Strap Included"]
  },
  {
    id: 7,
    name: "Stainless Steel Water Bottle",
    price: 29.99,
    originalPrice: null,
    category: "sports",
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&h=400&fit=crop",
    rating: 4.5,
    reviews: 756,
    badge: "Popular",
    description: "Double-walled insulated water bottle that keeps drinks cold for 24 hours and hot for 12 hours. BPA-free and leak-proof.",
    features: ["Double-Wall Insulation", "24hr Cold / 12hr Hot", "BPA-Free", "Leak-Proof"]
  },
  {
    id: 8,
    name: "Wireless Charging Pad",
    price: 34.99,
    originalPrice: 49.99,
    category: "electronics",
    image: "https://images.unsplash.com/photo-1586816879360-004f5b0c51e5?w=400&h=400&fit=crop",
    rating: 4.2,
    reviews: 198,
    badge: "Sale",
    description: "Fast wireless charging pad compatible with all Qi-enabled devices. Sleek, minimal design with LED indicator and anti-slip surface.",
    features: ["15W Fast Charging", "Qi Compatible", "LED Indicator", "Anti-Slip"]
  },
  {
    id: 9,
    name: "Canvas Backpack",
    price: 64.99,
    originalPrice: null,
    category: "fashion",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop",
    rating: 4.6,
    reviews: 445,
    badge: null,
    description: "Durable canvas backpack with padded laptop compartment, multiple pockets, and water-resistant coating. Perfect for daily commute or travel.",
    features: ["Laptop Compartment", "Water Resistant", "Multiple Pockets", "Padded Straps"]
  },
  {
    id: 10,
    name: "Ceramic Plant Pot Set",
    price: 39.99,
    originalPrice: 54.99,
    category: "home",
    image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=400&h=400&fit=crop",
    rating: 4.3,
    reviews: 167,
    badge: "Sale",
    description: "Set of 3 minimalist ceramic plant pots with drainage holes and bamboo saucers. Perfect for succulents, herbs, and small plants.",
    features: ["Set of 3", "Drainage Holes", "Bamboo Saucers", "Minimalist Design"]
  },
  {
    id: 11,
    name: "Aromatherapy Candle Set",
    price: 32.99,
    originalPrice: null,
    category: "home",
    image: "https://images.unsplash.com/photo-1602607616906-bd0e2d271e2c?w=400&h=400&fit=crop",
    rating: 4.7,
    reviews: 523,
    badge: "Popular",
    description: "Set of 4 hand-poured soy wax candles with essential oils. Scents include lavender, vanilla, eucalyptus, and sandalwood.",
    features: ["Soy Wax", "Essential Oils", "4 Scents", "40-Hour Burn Time"]
  },
  {
    id: 12,
    name: "Fitness Resistance Bands",
    price: 19.99,
    originalPrice: 29.99,
    category: "sports",
    image: "https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=400&h=400&fit=crop",
    rating: 4.4,
    reviews: 678,
    badge: "Sale",
    description: "Set of 5 resistance bands with different resistance levels. Great for home workouts, rehabilitation, and strength training.",
    features: ["5 Resistance Levels", "Latex-Free", "Carry Bag Included", "Exercise Guide"]
  }
];
